FROM gradle:8.10-jdk17-graal
LABEL maintainer="Pierce Le <hale0087@uni.sydney.edu.au>"
WORKDIR /app
COPY . .

ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD

ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

RUN gradle build
EXPOSE 8080
CMD gradle run
